# docker-compose.yml
version: '3.8'
services:
  frontend:
    build: ./emptycup-app
    ports:
      - "80:80" 
    volumes:
      - ./emptycup-app:/app 
      - /app/node_modules
    environment:
      
      - VITE_FIREBASE_API_KEY=AIzaSyA63zCxwsq-3n-VRdHM7OEEGfelukQV5e4
      - VITE_FIREBASE_AUTH_DOMAIN=emptycupapp.firebaseapp.com
      - VITE_FIREBASE_PROJECT_ID=emptycupapp
      - VITE_FIREBASE_STORAGE_BUCKET=emptycupapp.firebasestorage.app
      - VITE_FIREBASE_MESSAGING_SENDER_ID=1067893833240
      - VITE_FIREBASE_APP_ID=1:1067893833240:web:129a7180a975a974f30d6d
     